### ISSUE TITLE
自機の音の実装

### ISSUE THREAD

**Issue by ItoSeiy** [ItoSeiy/2DShooting-Late-presentation#143]

**Comment by KanbaraRyusei** [comment]
- [x] アイテムを拾った時の音
- [x] 通常弾の音
- [x] 精密操作時の弾の音
- [x] 被弾時の音
- [x] １UP時の音
- [x] ボムアイテム獲得時の音
- [x] レベルアップ時の音
- [x] Invincibleモードのときの音
